TARGET = main
# Define the linker script location and chip architecture.
LD_SCRIPT = STM32F446RETX_FLASH.ld
MCU_SPEC  = cortex-m4
# Toolchain definitions (ARM bare metal defaults)
CC = arm-none-eabi-gcc
AS = arm-none-eabi-as
LD = arm-none-eabi-ld
OC = arm-none-eabi-objcopy
OD = arm-none-eabi-objdump
OS = arm-none-eabi-size

# Assembly directives.
ASFLAGS += -c
ASFLAGS += -O0
ASFLAGS += -mcpu=$(MCU_SPEC)
ASFLAGS += -mthumb
ASFLAGS += -Wall

# (Set error messages to appear on a single line.)
ASFLAGS += -fmessage-length=0

# C compilation directives
CFLAGS += -mcpu=$(MCU_SPEC)
CFLAGS += -mthumb
CFLAGS += -Wall
CFLAGS += -g

# (Set error messages to appear on a single line.)
CFLAGS += -fmessage-length=0

# (Set system to ignore semihosted junk)
CFLAGS += --specs=nosys.specs

# Linker directives.
LSCRIPT = ./$(LD_SCRIPT)
LFLAGS += -mcpu=$(MCU_SPEC)
LFLAGS += -mthumb
LFLAGS += -Wall
LFLAGS += --specs=nosys.specs
LFLAGS += -nostdlib
LFLAGS += -lgcc
LFLAGS += -T$(LSCRIPT)
VECT_TBL = ./startup_stm32f446retx.S
C_SRC    = ./main.c
OBJS =  $(VECT_TBL:.S=.o)
OBJS += $(C_SRC:.c=.o)

# STM Link
STM_FLASHER = ST-LINK_CLI.exe
START_ADDRESS = 0x08000000

.PHONY: all, clean

all: $(TARGET).bin

%.o: %.S
	$(CC) -x assembler-with-cpp $(ASFLAGS) $< -o $@

%.o: %.c
	$(CC) -c $(CFLAGS) $(INCLUDE) $< -o $@

$(TARGET).elf: $(OBJS)
	$(CC) $^ $(LFLAGS) -o $@

$(TARGET).bin: $(TARGET).elf
	$(OC) -S -O binary $< $@
	$(OS) $<

flash: all
	$(STM_FLASHER) -P $(TARGET).bin $(START_ADDRESS) -V -Rst
	@echo Flashing done.

erase:
	$(STM_FLASHER) -ME

connect:
	$(STM_FLASHER) -c

clean:
	rm -f $(OBJS)
	rm -f $(TARGET).elf
	rm -f $(TARGET).bin
